apiVersion: apps/v1
kind: Deployment
metadata:
  name: one 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: one
  template:
    metadata:
      labels:
        app: one
    spec:
      containers:
      - name: one
        image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: "Welcome to Azure Kubernetes Service (AKS)"
---
apiVersion: v1
kind: Service
metadata:
  name: one
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: one

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-ingress-one
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging-devops
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
  - hosts:
    - one.devopslabs.live
    secretName: one.devopslabs.live-tls
  rules:
  - host: one.devopslabs.live
    http:
      paths:
      - backend:
          service:
            name: one
            port:
              number: 80
        path: /
        pathType: Prefix   