apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: devops
spec:
  selector:
    matchLabels:
      name: sonarqube
  replicas: 1    
  template:
    metadata:
      labels:
        name: sonarqube
    spec:
      initContainers:
      - name: init
        image: busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
      containers:
        - name: sonarqube
          image: sonarqube:8.9.2-community        
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 500m
              memory: 1024Mi
            limits:
              cpu: 2000m
              memory: 7048Mi
          volumeMounts:
          - mountPath: /opt/sonarqube/data/
            name: sonar-data
          - mountPath: /opt/sonarqube/extensions/
            name: sonar-extensions
          env:

          - name: "SONARQUBE_JDBC_URL"
            value: "jdbc:postgresql://postgres:5432/sonarqube"
          - name: "SONARQUBE_JDBC_USERNAME"
            valueFrom:
               secretKeyRef:
                 name: postgres-secrets
                 key: username
          - name: "SONARQUBE_JDBC_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: password                 
          ports:
          - containerPort: 9000
            protocol: TCP
      volumes:
      - name: sonar-data
        persistentVolumeClaim:
          claimName: sonar-data-pvc
          
      - name: sonar-extensions
        persistentVolumeClaim:
         claimName: sonar-extersion-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: devops
  labels:
    app: sonarqube
  annotations: 
    sonarqube: sonarqube check vulnerability 
    #service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  #loadBalancerIP: 172.21.0.200
  ports:
    - name: sonarqube
      port: 80
      protocol: TCP
      targetPort: 9000
  selector:
    name: sonarqube