# Redirect to https
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: devops
spec:
  redirectScheme:
    scheme: https
    permanent: true