apiVersion: apps/v1
kind: Deployment
metadata:
  name: two 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: two
  template:
    metadata:
      labels:
        app: two
    spec:
      containers:
      - name: two
        image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: "Welcome to Azure Kubernetes Service (AKS) BRUNO"
---
apiVersion: v1
kind: Service
metadata:
  name: two
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: two

---    
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-ingress-two
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging-devops
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
  - hosts:
    - two.devopslabs.live
    secretName: two.devopslabs.live.tls
  rules:
  - host: two.devopslabs.live
    http:
      paths:
      - backend:
          service:
            name: two
            port:
              number: 80
        path: /
        pathType: Prefix   